development:
  adapter: postgresql
  encoding: unicode
  database: liscio_dev_test
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: liscio_dev_test
  pool: 5

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 